Natural Language Processing

1. Split feature and target
2. Tokenization
3. Bag of Words (BoW)
4. n grams
5. tfidf

6. PREDICT

In [51]:
import pandas as pd
import numpy as np

In [52]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/CDSS/Data Folder/Womens Clothing E-Commerce Reviews.csv', encoding ="utf8")
df = df.sample(frac=1, random_state=10) #to create a random environment

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [53]:
df.head()

Unnamed: 0  Clothing ID  Age                   Title  \
9170         9170          862   36                     Fun   
9346         9346          895   31             Great tunic   
6249         6249          836   42                     NaN   
17481       17481         1086   45      Feels like a dream   
5204         5204          854   44  This top surprised me!   

                                             Review Text  Rating  \
9170   These tanks are perfect for working out! they ...       4   
9346   I love this tunic. i am 22 weeks pregnant and ...       5   
6249   Fit is boxy yet flattering and material is she...       5   
17481  This dress is so soft, flowy and comfortable! ...       5   
5204   This too is easy to wear, skins the body nicel...       5   

       Recommended IND  Positive Feedback Count Division Name Department Name  \
9170                 1                        0       General            Tops   
9346                 1                        0       General            Tops   
6249                 1                        0       General            Tops   
17481                1                        1       General         Dresses   
5204                 1                        1       General            Tops   

       Class Name  
9170        Knits  
9346   Fine gauge  
6249      Blouses  
17481     Dresses  
5204        Knits

In [4]:
len(df)

23486

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23486 entries, 9170 to 17673
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.2+ MB


In [6]:
df.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [7]:
df.Rating.unique()

array([4, 5, 3, 2, 1])

In [54]:
# Drop missing values
df.dropna(inplace=True)

# Remove any 'neutral' ratings equal to 3
df = df[df['Rating'] != 3]

# Encode 4s and 5s as 1 (rated positively)
# Encode 1s and 2s as 0 (rated poorly)
# if greater than 3, make it as 1, otherwise 0
df['Positively Rated'] = np.where(df['Rating'] > 3, 1, 0)

<ipython-input-54-663725b7b186>:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Positively Rated'] = np.where(df['Rating'] > 3, 1, 0)


In [55]:
df.isnull().sum()

Unnamed: 0                 0
Clothing ID                0
Age                        0
Title                      0
Review Text                0
Rating                     0
Recommended IND            0
Positive Feedback Count    0
Division Name              0
Department Name            0
Class Name                 0
Positively Rated           0
dtype: int64

In [10]:
df.head()

Unnamed: 0  Clothing ID  Age                   Title  \
9170         9170          862   36                     Fun   
9346         9346          895   31             Great tunic   
17481       17481         1086   45      Feels like a dream   
5204         5204          854   44  This top surprised me!   
22682       22682          862   62   Gorgeously draped top   

                                             Review Text  Rating  \
9170   These tanks are perfect for working out! they ...       4   
9346   I love this tunic. i am 22 weeks pregnant and ...       5   
17481  This dress is so soft, flowy and comfortable! ...       5   
5204   This too is easy to wear, skins the body nicel...       5   
22682  This top is extremely well made. the fabric is...       5   

       Recommended IND  Positive Feedback Count   Division Name  \
9170                 1                        0         General   
9346                 1                        0         General   
17481                1                        1         General   
5204                 1                        1         General   
22682                1                        4  General Petite   

      Department Name  Class Name  Positively Rated  
9170             Tops       Knits                 1  
9346             Tops  Fine gauge                 1  
17481         Dresses     Dresses                 1  
5204             Tops       Knits                 1  
22682            Tops       Knits                 1

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17198 entries, 9170 to 7293
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               17198 non-null  int64 
 1   Clothing ID              17198 non-null  int64 
 2   Age                      17198 non-null  int64 
 3   Title                    17198 non-null  object
 4   Review Text              17198 non-null  object
 5   Rating                   17198 non-null  int64 
 6   Recommended IND          17198 non-null  int64 
 7   Positive Feedback Count  17198 non-null  int64 
 8   Division Name            17198 non-null  object
 9   Department Name          17198 non-null  object
 10  Class Name               17198 non-null  object
 11  Positively Rated         17198 non-null  int64 
dtypes: int64(7), object(5)
memory usage: 1.7+ MB


# Model Selection in scikit-learn

In [57]:
from sklearn.model_selection import train_test_split

# Split data into train and test subsets
X_train, X_test, y_train, y_test = train_test_split(df['Review Text'],
                                                    df['Positively Rated'],
                                                    random_state=0)

In [58]:
print( X_train.iloc[2])



Disappointed :-(
this top has a boxy shape and looked like a mini moo moo on me. i have a similar shape as the model and it looked nothing like that on me. bummer! i liked the quality and weight (not too heavy nor too light) but shape is unflattering. it's going back.


In [59]:
X_train.shape

(12898,)

In [60]:
X_test.shape

(4300,)

# Extracting features from text files


Text files are actually series of words (ordered). In order to run machine learning algorithms we need to convert the text files into numerical feature vectors. We will be using bag of words model.

## Bag-of-words (BOW)
BOW model allows us to represent text as numerical feature vectors. The idea behind BOW is quite simple and can be summarized as follows:
- 1) Create a vocabulary of unique tokens (or words) from the entire set
    of documents.
- 2) Construct a feature vector from each document that contains the counts of how often each word occurs in the particular document.

Since the unique words in each document represent only a small subset of all the words in the bag-of-words vocabulary, the feature vectors will consist of mostly zeros, which is why we call them sparse. For this reason we say that bags of words are typically <b>high-dimensional sparse datasets</b>.

{for our example. Briefly, we segment each text file into words (for English splitting by space), and count # of times each word occurs in each document and finally assign each word an integer id. Each unique word in our dictionary will correspond to a feature (descriptive feature).}


### Transform words into vectors (CountVectorizer)
To construct a bag-of-words model based on the word counts in the respective documents, we can use the `CountVectorizer` class implemented in `scikit-learn`. As we will see in the following codes, the `CountVectorizer` class takes an array of text data, which can be documents or just sentences, and constructs the bag-of-words model for us:

Scikit-learn has a high level component which will create feature vectors for us <b>‘CountVectorizer’</b>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

docs = np.array([
    'The sun is shining',
    'The weather is sweet',
    'The sun is shining and the weather is sweet'])

# Fit the CountVectorizer to the training data
vect1=CountVectorizer().fit(docs)

# transform the documents in the training data to a document-term matrix.
bag1 = vect1.transform(docs)

#vector is number format

In [ ]:
vect1.vocabulary_

{'the': 5, 'sun': 3, 'is': 1, 'shining': 2, 'weather': 6, 'sweet': 4, 'and': 0}

In [ ]:
vect1.get_feature_names_out()

array(['and', 'is', 'shining', 'sun', 'sweet', 'the', 'weather'],
      dtype=object)

## <font color=green> Exercise A</font>

1) Do CountVectorizer for training data

2) Determine:
- The number of features
- The shape of sparse matrix

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

# Fit the CountVectorizer to the training data
review1 = CountVectorizer().fit(X_train)

# transform the documents in the training data to a document-term matrix.
X_train_vectorized1 = review1.transform(X_train)


print(len(review1.get_feature_names_out()))
X_train_vectorized1.shape

# for BOW, raw data is review1, and bag is vectorized1
# output
# (num of observation, num of columns/keywords)

11436


(12898, 11436)

In [17]:
X_test_vectorized1 = review1.transform(X_test)
X_test_vectorized1.shape

(4300, 11436)

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into train and test subsets
X_train, X_test, y_train, y_test = train_test_split(df['Review Text'],
                                                    df['Positively Rated'],
                                                    random_state=0)

# Train the Logistic Regression model
lm = LogisticRegression()
lm.fit(X_train_vectorized1, y_train)

# Evaluate the model on the test data
accuracy = lm.score(X_test_vectorized1, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9279069767441861


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:
review1.vocabulary_

{'love': 5974,
 'these': 10141,
 'pants': 7145,
 'they': 10143,
 'are': 883,
 'so': 9245,
 'soft': 9259,
 'and': 761,
 'comfortable': 2290,
 'do': 3191,
 'not': 6754,
 'fall': 3825,
 'down': 3238,
 'like': 5813,
 'low': 5987,
 'rise': 8375,
 'trousers': 10451,
 'the': 10114,
 'length': 5749,
 'for': 4188,
 'wearing': 11030,
 'with': 11214,
 'flats': 4050,
 'most': 6485,
 'wide': 11153,
 'bottom': 1511,
 'too': 10310,
 'long': 5908,
 'very': 10852,
 'casual': 1879,
 'to': 10283,
 'be': 1190,
 'worn': 11274,
 'absolutely': 457,
 'this': 10172,
 'sweater': 9875,
 'because': 1224,
 'it': 5355,
 'is': 5341,
 'pretty': 7689,
 'while': 11117,
 'being': 1255,
 'am': 725,
 'purchased': 7849,
 'small': 9172,
 'falls': 3831,
 'little': 5874,
 'below': 1272,
 'my': 6568,
 'hips': 4864,
 'color': 2244,
 'matches': 6168,
 'everything': 3654,
 'pockets': 7511,
 'details': 3005,
 'add': 540,
 'nice': 6687,
 'touch': 10343,
 'longer': 5909,
 'sleeves': 9104,
 'cozy': 2600,
 'only': 6889,
 'drawback': 3

In [20]:
review1.get_feature_names_out()

array(['00', '00p', '02', ..., 'zooming', 'zuma', 'ã¼ber'], dtype=object)

# Logistic Regression classification

We will train a logistic regression model to classify the  Amazon reviews into positive and negative reviews by using feature matrix.

In [21]:
from sklearn.metrics import roc_auc_score

# Predict the transformed test documents
predictions = lm.predict(review1.transform(X_test))
y_proba = lm.predict_proba(review1.transform(X_test))

print('AUC: ', roc_auc_score(y_test, y_proba[:,1]))

AUC:  0.9468811638062624


In [22]:
# coefficient of each keywords
# lower coefficient = -ve review
lm.coef_

array([[-0.13649485,  0.22374376,  0.07265229, ...,  0.01214997,
         0.00223398,  0.00061616]])

In [23]:
lm.coef_[0].argsort()

array([4941, 1980, 1063, ...,  284, 9270, 2358])

In [24]:
# get the feature names as numpy array
feature_names = np.array(review1.get_feature_names_out())

# Sort the coefficients from the model
sorted_coef_index = lm.coef_[0].argsort()

# Find the 10 smallest and 10 largest coefficients
print('Smallest Coefs:' )
print(feature_names[sorted_coef_index[  :10]])

print('\n Largest Coefs:')   #\n is for line space
print(feature_names[sorted_coef_index[  :-11:-1]]) #select last 10 values

Smallest Coefs:
['horrible' 'cheap' 'awful' 'completely' 'disappointed' 'poor'
 'unflattering' 'wanted' 'nothing' 'disappointment']

 Largest Coefs:
['compliments' 'sold' '34' 'happy' 'unique' 'paired' 'beautifully'
 'stunning' 'little' 'deep']


# Tfidf

When we are analyzing text data, we often encounter words that occur across multiple documents from both classes. Those frequently occurring words typically don't contain useful or discriminatory information. In this subsection, we will learn about a useful technique called **term frequency-inverse document frequency** (*tf-idf*) that can be used to downweight those frequently occurring words in the feature vectors. On the other words by tf-idf we can reduce the weightage of more common words like (the, is, an etc.) which occurs in all document.

The *tf-idf* can be defined as the product of the term frequency and the inverse document frequency:

\begin{align}
\textit{tf-idf}(t,d) = tf(t,d) \times idf(t,d)
\end{align}

Here the <font color=green><b> *tf(t,d)* </b></font> is the term frequency that equal to **Count of word / Total words, in each document**. The inverse document frequency *idf(t,d)* can be calculated as:

\begin{align}
idf(t,d) = log\frac{n_d}{\text{df(d,t)}}
\end{align}

where <font color=green><b> $n_d$ </b></font> is **the total number of documents**, and <font color=green><b>*df(d,t)*</b></font> is **the number of documents *d* that contain the term t**. Note that the log is used to ensure that low document frequencies are not given too much weight.


scikit-learn implements yet another vectorizer, the TfidfVectorizer, that creates feature vectors as tf-idfs.


In [ ]:
# to remove standard english stop words
from sklearn.feature_extraction.text import TfidfVectorizer

docs = np.array([
    'The sun is shining',
    'The weather is sweet',
    'The sun is shining and the weather is sweet'])

vect2 = TfidfVectorizer().fit(docs)
bag2 = vect2.transform(docs)

# trained data is vect2
# bag data is bag2

In [ ]:
vect2.get_feature_names_out()

array(['and', 'is', 'shining', 'sun', 'sweet', 'the', 'weather'],
      dtype=object)

In [ ]:
vect3 = TfidfVectorizer(min_df=2).fit(docs)
bag3 = vect3.transform(docs)
vect3.get_feature_names_out()

array(['is', 'shining', 'sun', 'sweet', 'the', 'weather'], dtype=object)

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Fit the TfidfVectorizer to the training data
review2 = TfidfVectorizer(min_df=5).fit(X_train)
X_train_vectorized2 = review2.fit_transform(X_train)

In [26]:
len(review2.get_feature_names_out())

3850

In [27]:
X_test_vectorized2 = review2.transform(X_test)
X_test_vectorized2.shape

(4300, 3850)

In [47]:
# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train_vectorized2, y_train)

# Evaluate the model on the test data
accuracy = model.score(X_test_vectorized2, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9253488372093023


In [29]:
X_train_vectorized2 = review2.transform(X_train)

model = LogisticRegression()
model.fit(X_train_vectorized2, y_train)

predictions = model.predict(review2.transform(X_test))
y_proba = model.predict_proba(review2.transform(X_test))

print('AUC: ', roc_auc_score(y_test, y_proba[:,1]))

AUC:  0.9571966710468682


## <font color=green> Exercise B</font>
- Predict two below reviews as negative or positive using our model:

      ['no an issue, phone is working', 'an issue, phone is not working']       

In [48]:
model.predict(review2.transform(['dress is very cute, love this']))

array([1])

Try this!

In [50]:
model.predict(review2.transform(['the material is cheap, disappointed even though the design is beautiful']))

array([0])

In [ ]:
# These reviews are now correctly identified
print(model.predict(review3.transform(['dress is very cute, love this',
                                    'the material is cheap, disappointed even though design is beautiful'])))

# n-grams

The sequence of items in the bag-of-words model that we just created is also called the 1-gram or unigram model — each item or token in the vocabulary represents a single word. Generally, <b>the contiguous sequences of items in NLP</b> — words, letters, or symbols— is also called an n-gram. The choice of the number n in the n-gram model depends on the particular application. For instance, spam filtering applications tend to use n=3 or n=4 for good performances.
To summarize the concept of the n-gram representation, the 1-gram and 2-gram representations of our first document "the sun is shining" would be constructed as follows:
- 1-gram: "the", "sun", "is", "shining"
- 2-gram: "the sun", "sun is", "is shining"

The CountVectorizer class in scikit-learn allows us to use different n-gram models via its ngram_range parameter. By default, it uses a 1-gram representation.

In [ ]:
# Try 2-gram representation
docs = np.array([
    'The sun is shining',
    'The weather is sweet',
    'The sun is shining and the weather is sweet'])

vect3=CountVectorizer(ngram_range=(1,2)).fit(docs)
bag3=vect3.transform(docs)

In [ ]:
vect3.vocabulary_

{'the': 10,
 'sun': 7,
 'is': 2,
 'shining': 5,
 'the sun': 11,
 'sun is': 8,
 'is shining': 3,
 'weather': 13,
 'sweet': 9,
 'the weather': 12,
 'weather is': 14,
 'is sweet': 4,
 'and': 0,
 'shining and': 6,
 'and the': 1}

In [32]:
review3 = CountVectorizer(min_df=5, ngram_range=(1,2)).fit(X_train)

X_train_vectorized3 = review3.transform(X_train)

In [33]:
len(review3.get_feature_names_out())

23333

In [34]:
X_test_vectorized3 = review3.transform(X_test)
X_test_vectorized3.shape

(4300, 23333)

In [35]:
# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train_vectorized3, y_train)

# Evaluate the model on the test data
accuracy = model.score(X_test_vectorized3, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.934186046511628


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [36]:
model = LogisticRegression()
model.fit(X_train_vectorized3, y_train)

predictions = model.predict(review3.transform(X_test))
y_proba = model.predict_proba(review3.transform(X_test))

print('AUC: ', roc_auc_score(y_test, y_proba[:,1]))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


AUC:  0.9566195463173124


In [37]:
feature_names = np.array(review3.get_feature_names_out())

sorted_coef_index = model.coef_[0].argsort()

print('Smallest Coefs:' )
print(feature_names[sorted_coef_index[:10]])

print('\n Largest Coefs:')
print(feature_names[sorted_coef_index[:-11:-1]])

Smallest Coefs:
['cheap' 'to love' 'unflattering' 'poor' 'disappointed' 'returned'
 'not flattering' 'completely' 'awful' 'very disappointed']

 Largest Coefs:
['compliments' 'very cute' 'not too' 'little' 'comfortable' 'beautiful'
 'unique' 'perfect' 'love this' 'great']


In [38]:
sorted_coef_index

array([ 4051, 20286, 20991, ..., 12897, 21332,  4541])

In [42]:
# These reviews are now correctly identified
print(model.predict(review3.transform(['dress is very cute, love this',
                                    'the material is cheap, disappointed even though design is beautiful'])))

[1 0]
